### ISSUE TITLE
Console warning when using Envira Lite Block w/Gutenberg

### ISSUE THREAD

**Issue by bmilligan15** [LionSher-Technologies/envira-gallery-lite#100]
Reported on .org(https://wordpress.org/support/topic/throws-warning-while-adding-gutenberg-block/), and I was able to replicate locally. Having trouble getting the error to format nicely in the ticket, so I'll attach an image, as well as my console log, to this ticket.

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/17555874/169110492-ae20768c-cc30-4041-bac7-c2caf9738306.png">

[localhost-1652896481430.log](https://github.com/LionSher-Technologies/envira-gallery-lite/files/8718939/localhost-1652896481430.log)

**Comment by dimensionmedia** [comment]
this should have been pushed out in today's release.
