### ISSUE TITLE
PHP 8.1 compatibility errors

### ISSUE THREAD

**Issue by greatknave** [LionSher-Technologies/envira-gallery-lite#106]
From .org: https://wordpress.org/support/topic/envira-gallery-lite-compatibility-with-php-8-x/

At PHP 8.1, these errors pop up:

Undefined array key "link" in /var/www/vhosts/vip-grinders.com/httpdocs/wp-content/plugins/envira-gallery-lite/includes/global/shortcode.php on line 1528

Warning: Undefined array key "title" in /var/www/vhosts/vip-grinders.com/httpdocs/wp-content/plugins/envira-gallery-lite/includes/global/shortcode.php on line 405

Warning: Undefined array key "alt" in /var/www/vhosts/vip-grinders.com/httpdocs/wp-content/plugins/envira-gallery-lite/includes/global/shortcode.php on line 482

Warning: Undefined array key "title" in /var/www/vhosts/vip-grinders.com/httpdocs/wp-content/plugins/envira-gallery-lite/includes/global/shortcode.php on line 482

**Comment by bmilligan15** [comment]
Adding another warning/notice to this ticket that's specific to 8.1.

PHP Deprecated:  usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /Users/bradmilligan/Local Sites/envira/app/public/wp-content/plugins/envira-gallery-lite/includes/global/rest.php on line 437

**Comment by bmilligan15** [comment]
Another mention on .org: https://wordpress.org/support/topic/php-warning-417/
