### ISSUE TITLE
Links not opening in new tab when directed to do so

### ISSUE THREAD

**Issue by greatknave** [LionSher-Technologies/envira-gallery-lite#108]
https://secure.helpscout.net/conversation/2120999023/119804?folderId=3302565

This user reports that when he's using links instead of the lightbox, and selects the option to open his links in a new tab, it doesn't work — it opens in the same tab, navigating away from the user's site. @bmilligan15 and I both tested this on local and on the testing environment, and we're able to replicate the issue:

https://testing.enviragallery.com/lite-testing/

https://testing.enviragallery.com/wp-admin/post.php?post=10054&action=edit

Make sure Lite is activated prior to visiting, of course.

**Comment by bmilligan15** [comment]
Another report: https://secure.helpscout.net/conversation/2147219701/120940?folderId=1769539
