### ISSUE TITLE
HTML Displaying in Image Titles on Envira Lite

### ISSUE THREAD

**Issue by bmilligan15** [LionSher-Technologies/envira-gallery-lite#62]
Customer submitted, but confirmed on lite.enviragallery.com. HTML is being displayed on the front end when added to the image titles. Simply hover the first two images, and you will see the HTML.

http://lite.enviragallery.com/2020/12/22/automatic-html-test/

https://secure.helpscout.net/conversation/1375852535/84160?folderId=1769539

SFTP
====
Host: danielbigaj.com
Username: danbig2
Password: s5dujbBIY$BS167923$%

WP-Admin
=========
https://jasmineschut.ca/wp-admin
envira
OsqEImgiizBkNVqE5aDNSQQM

![Screen Shot 2020-12-22 at 7 58 00 AM](https://user-images.githubusercontent.com/17555874/102891095-a6580180-442b-11eb-8571-6aa78221509a.png)
![Screen Shot 2020-12-22 at 7 58 27 AM](https://user-images.githubusercontent.com/17555874/102891096-a6f09800-442b-11eb-89ea-49e795a44a86.png)

**Comment by bmilligan15** [comment]
Customer is requesting an update: https://secure.helpscout.net/conversation/1375852535/84160?folderId=4156775

**Comment by dimensionmedia** [comment]
@bmilligan15 @greatknave i'll ping on Slack but i have code to test on lite.enviragallery.com.

**Comment by greatknave** [comment]
Tested!

Titles now accept links, basic HTML like bold, italics, etc.

**Comment by bmilligan15** [comment]
This has been resolved. Thank you!
