### ISSUE TITLE
PHP 8 issue

### ISSUE THREAD

**Issue by greatknave** [LionSher-Technologies/envira-gallery-lite#63]
https://secure.helpscout.net/conversation/1390036267/84872/

This user has Lite on a local install with PHP 8 running. When he tries to access the addons link (where we upsell), he sees this:

![image](https://user-images.githubusercontent.com/56563598/104355779-00defd80-54c0-11eb-9a89-dc40d57e6803.png)

**Comment by dimensionmedia** [comment]
Just tested this with PHP 8 locally and couldn't duplicate.

**Comment by dimensionmedia** [comment]
@greatknave after latest update can you confirm if oringial issue is still happening? thanks.
