### ISSUE TITLE
WPScripts localize warning

### ISSUE THREAD

**Issue by dimensionmedia** [LionSher-Technologies/envira-gallery-lite#67]
![Screen Shot 2021-03-26 at 11 08 42 AM](https://user-images.githubusercontent.com/721134/112675252-4e230800-8e3d-11eb-9198-b0da64c1ea27.png)

**Comment by bmilligan15** [comment]
Another report (also posted on .org): https://secure.helpscout.net/conversation/1490004249/90153?folderId=4156775

**Comment by greatknave** [comment]
Reporting: https://secure.helpscout.net/conversation/1510801666/90980?folderId=1769544

**Comment by bmilligan15** [comment]
No longer seeing this notice with debugging enabled. Thank you!
