### ISSUE TITLE
Enhancement: Lazy Loading filter for SG Optimizer plugin (similar to our Jetpack filter)

### ISSUE THREAD

**Issue by bmilligan15** [LionSher-Technologies/envira-gallery-lite#78]
A user is reporting that full sized gallery images are loading below the gallery thumbnails when lazy loading is enabled within the SG Optimizer plugin. I was able to confirm this as well, and this is only occurring on Envira Lite. For a workaround, I recommended to him to temp. disable lazy loading within the SG Optimizer plugin. We tried to exclude the .envira-gallery-image class within that plugin, but was unsuccessful.

We had this same behavior for a minute with Jetpack's Lazy Loading feature, and @dimensionmedia created a filter to handle/resolve this (https://enviragallery.com/docs/how-to-use-jetpack-lazy-load-and-enviras-lazy-load-together/). I'm wondering if we can create something similar for the SiteGround Optimizer plugin?

You can see a live example here: https://www.staging13.secretsofuniverse.in/history-of-life-sou/

I'll update the ticket if I'm able to get any access from the client.

**Comment by bmilligan15** [comment]
Confirmed working on testing/w Envira Lite. Thank you!

**Comment by dimensionmedia** [comment]
This was done with a plugin. Full code here for reference. @bmilligan15 @greatknave 

```
<?php
/*
* Plugin Name: Envira Gallery - SiteGround Optimizator Filter
* Plugin URI: https://enviragallery.com
* Version: 1.0.0
* Author: Envira Gallery Team
* Author URI: https://enviragallery.com
* Description: Allowing SG lazy load and Envira lazy load to work in harmony
*/

add_filter('sgo_lazy_load_exclude_classes', 'egsof_sgo_lazy_load_exclude_classes', 999, 1 );
function egsof_sgo_lazy_load_exclude_classes( $blacklisted_classes ) {
    if ( ! in_array( 'envira-gallery-image', $blacklisted_classes ) ) {
        $blacklisted_classes[] = 'envira-gallery-image';
    }
    if ( ! in_array( 'skip-lazy', $blacklisted_classes ) ) {
        $blacklisted_classes[] = 'skip-lazy';
    }
    return $blacklisted_classes;
}

add_filter('envira_gallery_indexable_images', 'esgof_envira_gallery_indexable_images', 999, 3 );
function esgof_envira_gallery_indexable_images( $images, $index, $id ) {
    $images = str_replace('<img ', '<img class="skip-lazy" ', $images);
    return $images;
}

```

**Comment by dimensionmedia** [comment]
@bmilligan15 @greatknave up to us if we want to add a support doc to this. leave this in your hands.
