### ISSUE TITLE
'Add Gallery' button missing within Classic Editor.

### ISSUE THREAD

**Issue by bmilligan15** [LionSher-Technologies/envira-gallery-lite#82]
Mentioned by a customer, and I was able to confirm locally. While using Envira Gallery Lite with the Classic Editor, the 'Add Gallery' button is no longer appearing above the editor. @dimensionmedia has already resolved this (thank you), so this is being added for documentation.

https://secure.helpscout.net/conversation/1657139556/96251?folderId=1769544

www.ad-astra.si/wp-admin
Matej
7SPcAy34@kea7O5ionOgxJL8

Customer will not provide FTP (he's not concerned about this issue, and is willing to wait for the next release).

<img width="1437" alt="Screen Shot 2021-10-22 at 9 30 15 AM" src="https://user-images.githubusercontent.com/17555874/138462144-4f3a9fc3-fc21-4ca1-975c-3c928caf61b7.png">
^^Lite with no Add Gallery button

<img width="1434" alt="Screen Shot 2021-10-22 at 9 29 58 AM" src="https://user-images.githubusercontent.com/17555874/138462195-08f90355-c289-4217-af30-1f2193c60979.png">
^^Pro with the Add Gallery button

**Comment by dimensionmedia** [comment]
This fix is rolling out with the next release, currently in master. Screenshots attached for the fix (change filter to action and echo just the $button).

![Screen Shot 2021-11-04 at 2 58 16 PM](https://user-images.githubusercontent.com/721134/140402770-2faf451c-3b7f-4caa-a8a6-83d178fc0e72.png)

**Comment by bmilligan15** [comment]
Confirmed. Thank you!
<img width="1440" alt="Screen Shot 2022-03-23 at 12 27 14 PM" src="https://user-images.githubusercontent.com/17555874/159748482-276ae032-ff3b-4142-b719-c7ead4721fa0.png">
