### ISSUE TITLE
Email and name text fields different heights

### ISSUE THREAD

**Issue by greatknave** [LionSher-Technologies/envira-gallery-lite#85]
<img width="603" alt="Screen Shot 2022-01-25 at 8 14 38 AM" src="https://user-images.githubusercontent.com/56563598/151015430-9e7c5bfb-4ae9-4498-8e58-d2107612fa0e.png">

At the top of the galleries-list page, this signup block has two fields, name and email address, that are of different heights.

**Comment by dimensionmedia** [comment]
Before/after

![Screen Shot 2022-04-05 at 3 23 19 PM](https://user-images.githubusercontent.com/721134/161834182-0030ea7a-1cba-4c19-87f4-aa1eca26d0f3.png)
![Screen Shot 2022-04-05 at 3 21 19 PM](https://user-images.githubusercontent.com/721134/161834183-41814a12-967f-4dc5-ba49-41e20d3d8cf9.png)
