### ISSUE TITLE
Clear Cache re: conflict with Enhanced Media Replace Pro issue

### ISSUE THREAD

**Issue by dimensionmedia** [LionSher-Technologies/envira-gallery-lite#87]
https://github.com/LionSher-Technologies/envira-gallery-plugin/commit/20cd9c6ac4570b646258389dca7dc8bf9016bc40

**Comment by dimensionmedia** [comment]
Note: This is the same issue https://github.com/LionSher-Technologies/envira-gallery-plugin/issues/4201

**Comment by bmilligan15** [comment]
We're good here. Thank you!
