### ISSUE TITLE
Conflict with 'Aggregate JS Files' setting in Autoptimize

### ISSUE THREAD

**Issue by bmilligan15** [LionSher-Technologies/envira-gallery-lite#94]
Reported on .org, and @dimensionmedia was able to replicate.

From the ticket:

_The Envira galleries on landing pages of my website breaks after I enable ‘Aggregate all linked JS-files to have them loaded non-render blocking’ function of Autoptimize plugin.

I have disabled it for now.

I want to enable it as it helps in faster loading and improving core web vitals score of Google._

![image](https://user-images.githubusercontent.com/17555874/165145994-9f23c428-85cb-419d-a09e-59820f8db4c2.png)

**Comment by dimensionmedia** [comment]
@bmilligan15 @greatknave i've concluded we can't do anything to Lite to just make this work so make sure customers are adding the jquery in the field, see screenshot.

```
wp-includes/js/jquery/jquery.js
```

![Screen Shot 2022-05-02 at 4 54 31 PM](https://user-images.githubusercontent.com/721134/166326090-375b0c54-051f-4c42-819d-ff3075fbf874.png)
