### ISSUE TITLE
Editor Icons Misaligned

### ISSUE THREAD

**Issue by dimensionmedia** [LionSher-Technologies/envira-gallery-lite#97]
See screenshot.

![Screen Shot 2022-05-12 at 10 33 43 AM](https://user-images.githubusercontent.com/721134/168101089-6eac4a6d-f4ca-43b2-8b00-071ada237be0.png)

**Comment by dimensionmedia** [comment]
should look better now.


![Screen Shot 2022-05-12 at 12 25 51 PM](https://user-images.githubusercontent.com/721134/168123368-82e73e5a-a1cc-43b3-b997-5d4081684d4e.png)

**Comment by greatknave** [comment]
I did. It was working on my local!

**Comment by greatknave** [comment]
Confirming it works on lite.eg, as well:

<img width="687" alt="Screen Shot 2022-05-18 at 8 14 50 AM" src="https://user-images.githubusercontent.com/56563598/169076908-56fb0ee0-96c3-494e-b30a-c456f22993bb.png">
